"""initial schema

Revision ID: 9cbf11af4572
Revises: 
Create Date: 2026-05-23 00:20:15.379609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cbf11af4572'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('custodian', sa.String(), nullable=False),
    sa.Column('brokerage_fee_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_class', sa.String(), nullable=False),
    sa.Column('tax_class', sa.String(), nullable=False),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('investor_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('risk_profile', sa.String(), nullable=False),
    sa.Column('horizon_years', sa.Integer(), nullable=False),
    sa.Column('monthly_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('monthly_expenses', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('questionnaire_answers', sa.JSON(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_objectives',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allocations_json', sa.JSON(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('tax_due', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tax_paid', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('accumulated_loss', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('darf_code', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('fees', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('irrf', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('tax_events')
    op.drop_table('portfolio_objectives')
    op.drop_table('investor_profiles')
    op.drop_table('assets')
    op.drop_table('accounts')
    # ### end Alembic commands ###
