"""suggested_portfolios

Revision ID: d94e8bfc79bb
Revises: 9cbf11af4572
Create Date: 2026-05-24 00:34:42.791120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd94e8bfc79bb'
down_revision: Union[str, Sequence[str], None] = '9cbf11af4572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggested_portfolios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('risk_profile_hint', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('class_allocations_json', sa.JSON(), nullable=False),
    sa.Column('asset_allocations_json', sa.JSON(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggested_portfolios')
    # ### end Alembic commands ###
