"""portfolio_snapshots

Revision ID: ef640883dd72
Revises: d94e8bfc79bb
Create Date: 2026-05-24 00:58:51.716166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef640883dd72'
down_revision: Union[str, Sequence[str], None] = 'd94e8bfc79bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('equity_positions_json', sa.JSON(), nullable=False),
    sa.Column('fixed_income_positions_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_snapshots')
    # ### end Alembic commands ###
